name: tb-sample-report-pipeline-plugin

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: mkdir output
      - run: build/build_workflow.sh . output
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: output/tb-sample-report-pipeline-plugin-${{ github.ref }}.jar
        asset_name: tb-sample-report-pipeline-plugin-${{ github.ref }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "M. tuberculosis sample report IRIDA plugin"      
